### PR TITLE
removed page meta information

### PR DESCRIPTION
**Pull request by bottlerocket**

### CODE REVIEW

**Comment by marcofucci** [comment]
👍

**Comment by Demotive** [comment]
Why only physio? Shouldn't we remove it in all pages if it's a problem?

**Comment by bottlerocket** [comment]
It's only on that page....so it seems.

**Comment by Demotive** [comment]
[Passive agressive screengrab]
screen shot 2016-07-22 at 13 00 45
[END Passive agressive screengrab]

**Comment by bottlerocket** [comment]
The diabetes and depression pages have been superseded by other work and no longer exist. However, to be thorough, I will update it regardless. Thanks Mat.

**Pull request merged**
