### PR TITLE
Rework README

### PR DESCRIPTION
**Pull request by Demotive**
Reworking and simplifying the README, removing misleading references to it being a "kit".
Removing docs, which were simply a duplicate of https://github.com/alphagov/govuk_prototype_kit.

Anyone have an opinion on renaming the repo itself?

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
I'd support renaming it to remove the word kit and make it more descriptive (?nhs-alpha-prototypes-xxx) where xxx is a date, sequence number or sprint number - assuming it is trivial to do.

**Comment by Demotive** [comment]
People should update their remotes, but it's not a breaking change to use a new repo name (see https://help.github.com/articles/renaming-a-repository/)

So something like `nhs-alpha-prototypes-january-2016` - January is when the last UI based PR went through?

**Comment by neilbmclaughlin** [comment]
Just thinking about how Steve P has set up a new prototype - he forked this repo and then added his prototype GP screens to it. Was thinking this might be how prototypes get done in future, in which case the naming scheme with dates sort of makes sense, but not sure this is a good model. Perhaps we should only have a single nhs-alpha-prototypes repo. I'd need to understand why Steve forked it.

**Comment by teneightfive** [comment]
I think renaming the repo would be a good move, but adding a date to it feels wrong. What about just using `nhs-alpha-prototypes`?

**Comment by teneightfive** [comment]
We need this change too though

**Comment by neilbmclaughlin** [comment]
Agreed - Steve is on holiday today - I'll merge the pull request and rename the repo to nhs-alpha-prototypes and we can discuss the fork separately next week.

**Comment by Demotive** [comment]
👍 
Raised an issue for the renaming task https://github.com/nhsalpha/nhs_prototype_kit/issues/194

**Comment by neilbmclaughlin** [comment]
Spoke to Steve P and the aim is to merge the gp-screens-prototype fork back into this repo.

**Pull request merged**
