### PR TITLE
Combine blood & organ donation into end screen

### PR DESCRIPTION
**Pull request by fawkesley**
Make the journey go:

```
dispense-medicines --> complete + blood/organs --> complete
```

Rather than

```
dispense-medicines --> blood --> organs --> complete
```

image

Add a query parameter to application-complete to flip between showing a
form and showing a "saved" message.

### CODE REVIEW

**Comment by pacharanero** [comment]
All looking good - although the phrase "Would you be prepared to give blood?" right after the appointment booking might be interpreted by some patients as meaning they might be asked to give the blood actually AT the appointment they are trying to make!

Perhaps "Would you like to register to donate blood in the future?"

Also: would some patients worry that if they aren't prepared to give blood, they would go to the back of the queue for appointments.

M

**Comment by fawkesley** [comment]
Interesting, I think these questions were copied verbatim off the
"official" form. But yes, we should make them better.

**Comment by fawkesley** [comment]
"the phrase "Would you be prepared to give blood?" right after the appointment booking might be interpreted by some patients as meaning they might be asked to give the blood actually AT the appointment they are trying to make!" - on second thoughts, this is actually the "register at a GP practice" journey so that's probably not such a concern

**Comment by fawkesley** [comment]
OK I've made a [separate pull request](https://github.com/nhsalpha/nhs_prototype_kit/issues/80) for discussing that wording change in order to separate that concern from this PR's purpose.

**Pull request merged**
